import type { Metadata } from "next";
import "../globals.css";
import Header from "@/shared/Header";

export const metadata: Metadata = {
  title: "NiNo Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Header />
      {children}
    </main>
  );
}
